---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myargcd-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      tool: argocd
  template:
    metadata:
      labels:
        tool: argocd
    spec:
      containers:
      - name: argocont
        image: dudishivaram/shop:dockerweb
        ports:
        - containerPort: 80
